development:
  adapter: mysql
  database: sample_app_development 
  login: root
  password: 

test: &test
  adapter: mysql
  database: sample_app_test
  login: root
  password: 

cucumber:
  <<: *test
